#!/bin/bash

# Import updates from main CVS repo

if ! git branch -l | grep -q upstream ; then
    git branch upstream origin/upstream
fi

# verbose args: -v -p-v
git-cvsimport -d :pserver:anoncvs@anoncvs.quagga.net:/var/cvsroot -k -u -i -m -o upstream quagga

# Annotate tags

git tag -l |
while read t ; do
    if [ ! -r .git/refs/tags/$t ] ; then
       r=$(git-show-ref -s $t)
       git tag -d $t
       git tag -a -m 'import cvs tag' $t $r
    fi
done

echo "Remember to: git push suva:/git/quagga.git upstream"
