#!/bin/bash -e

#create linkstatus directory for watchlink process
mkdir /var/linkstatus 2>/dev/null

if [ -n "$DEBIAN_SCRIPT_DEBUG" ]; then set -v -x; DEBIAN_SCRIPT_TRACE=1; fi
${DEBIAN_SCRIPT_TRACE:+ echo "#42#DEBUG# RUNNING $0 $*"}

# This is most likely due to the answer "no" to the "really stop the server"
# question in the prerm script.
if [ "$1" = "abort-upgrade" ]; then
  exit 0
fi

. /usr/share/debconf/confmodule

db_stop

#DEBHELPER#

